### ISSUE TITLE
Ошибка при валидации адресов электронной почты в доменах .рф

### ISSUE THREAD

**Issue by Sky-Cat** [romeOz/rock-validate#1]
При проверке email в домене .рф всегда выдает ошибку.

Примеры адресов: contact@золотой-ларец.рф, contact@xn----8sbpfklcuba0as3d.xn--p1ai

**Comment by romeOz** [comment]
Благодарю. 
Добавил ([0.12.1](https://github.com/romeOz/rock-validate/releases/tag/0.12.1)) возможность использования unicode-символов в email-е, а также поддержку IPv4/IPv6 в домене:

``` php
v::email()->validate('site@[255.255.255.255].com'); // output: true

v::email()->validate('site@[IPv6:2001:db8:1ff::a0b:dbd0].com'); // output: true
```

К слову, в PHP 7.1 к функции `filter_var()` [добавили константу `FILTER_FLAG_EMAIL_UNICODE`](https://github.com/php/php-src/blob/php-7.1.0RC3/UPGRADING#L216), но, к сожалению, корректно отрабатывает только с именем email-а - домен по-прежнему должен быть на латинице (ASCII). Так что без полифила пока никак.
